### PR TITLE
STOR-2007: Rebase to upstream v10.26.0 for OCP 4.18

### PR DESCRIPTION
**Pull request by dfajmon**
Issue link:
https://issues.redhat.com/browse/STOR-2007

Diff to upstream v10.26.0:
https://github.com/Azure/azure-storage-azcopy/compare/v10.26.0...dfajmon:rebase-10.26.0

Changes between 10.25.1 (OCP 4.17) and 10.26.0 (OCP 4.18):
- https://github.com/Azure/azure-storage-azcopy/pull/2728
- https://github.com/Azure/azure-storage-azcopy/pull/2710
- https://github.com/Azure/azure-storage-azcopy/pull/2705

Full changelogs:
https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.26.0

@openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
~@dfajmon can you please update `.ci-operator.yaml` and Dockerfile with today's `main`? It was updated to 4.18.~

edit: ART will sync the files automatically

**Comment by dfajmon** [comment]
@ropatil010 can you check the status on this one please?

**Comment by ropatil010** [comment]
Adding label based on the test results.

Profile: ipi-on-azure/versioned-installer-ci
Platform: Azure
Payload: 4.18.0-0.test-2024-09-26-145156-ci-ln-zzim4x2-latest

Azure disk driver version:
oc logs pod/azure-disk-csi-driver-controller-7c578d575-6rdmk -c csi-driver
{"name":"disk.csi.azure.com","vendor_version":"v1.30.4"}
Azure file driver version:
oc logs pod/azure-file-csi-driver-controller-85b549c788-jswp2 -c csi-driver
{"name":"file.csi.azure.com","vendor_version":"v1.30.5"}
Az copy version:
oc exec -it pod/azure-file-csi-driver-controller-85b549c788-jswp2 -n openshift-cluster-csi-drivers -c csi-driver /bin/bash
bash-5.1$ /bin/./azcopy --version
azcopy version 10.26.0
For Azure File driver:
quay.io/rhn_support_ropatil/azfile@sha256:1c7f0be9da9823f250e4e698899e66b275c6fe79a98545dd363d7c77c63c189f

https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/ginkgo-test/271329/console
10-01 19:01:18.049 109 pass, 159 skip (2h50m56s)

/label qe-approved

**Pull request merged**
